### ISSUE TITLE
Admin permissions

### ISSUE THREAD

**Issue by jeancochrane** [fpdcc/document-search#16]
We need three types of admins:

* Read
* Read/Write
* Read/Write/Administer users

**Comment by glw** [comment]
Read and Read/Write are working correctly. I do not see Read/Write/Administer as a possible selection.

**Comment by jeancochrane** [comment]
Django has a built-in permission level, "Staff status", that controls whether or not a user can log into the admin site. Since the only thing you can do on the admin site is administer users, we use this permission level to control whether a user can administer other users.

There's a checkbox above the Group permissions box that controls whether or not a user has Staff status. The distinction is kind of confusing, but Staff status exists in concert with Groups, so a user can be in a group (e.g. Read/Write) and also have Staff status. My recommendation is to add all admin users to the Read/Write group and also give them Staff status.

I updated the documentation (section 2.6, "Administering Users") to explain this in more detail, but let me know if you feel like it's still not clear and I can add some words.

**Comment by glw** [comment]
Ok, thanks for the clarification Jean!
