### ISSUE TITLE
Preserve document change history

### ISSUE THREAD

**Issue by jeancochrane** [fpdcc/document-search#38]
Implement a simple change history system for documents. On document detail pages, display the change history as a new table below the PDF detail view; also create an admin-only global change view that shows a simple DataTables-enabled table with a list of all changes to the app.

Definitely record timestamp, user, and document changed. Take a look and see how hard it would be to add field to the mix as well.

**Comment by glw** [comment]
Just a note to document what we discussed in our check-in. 

- Update to allow all users to see recent changes.
