### ISSUE TITLE
Add About page for document type descriptions

### ISSUE THREAD

**Issue by jeancochrane** [fpdcc/document-search#39]
The document types available in the application may not be self-explanatory to all users. Let's add a simple `About` page with text from @glw that explains what each document type is, and add some help text to the app linking out to it.

**Comment by glw** [comment]
Hi Jean content for About page is below:

About page
This Document Search App is how the Planning and Development department of the Forest Preserves of Cook County catalogs many of its project documents. Below is a brief description of each category.

•	Books – Surveyor field notebooks.
•	Control Monument Maps – Documentation on placement of monument markers.
•	Surplus Parcels – Documentation on surplus parcels.
•	Deep Tunnels – MWRD Deep Tunnel project documentation.
•	Dossiers – Title Policies, Abstracts, Appraisals, other misc. documents
•	Easements – Documentation on easements.
•	Flat Drawings – Drawings of projects managed by the Planning and Development Dept. These would include; buildings, trails, and parking lots.
•	Index Cards – Survey monument records
•	Licenses – Licenses issued by the District.
•	Project Files – Planning and Development project files.
•	Rights of Way – Documentation on right of ways within District property.
•	Surveys – Surveys of property acquired by the District.
•	Titles – Titles, Deeds, Judgment Orders of property acquired by the District

Additional documentation on using the app is available here [Link to documentation].

**Comment by glw** [comment]
everything looks good here. Thanks Jean!
