### ISSUE TITLE
return to previous view/line of search results instead of top of page

### ISSUE THREAD

**Issue by glw** [fpdcc/document-search#55]
User feedback:
"In the search results page once you “view details” of one result and then return back to the  results page you return to the top of the page. Can the return take you back to the line were you previously selected “view details” ".

**Comment by jeancochrane** [comment]
I love this idea. I'm imagining we would do it by updating each search result to have an `id` attribute corresponding to the ID of the document, and then use [URL fragment identifiers](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash) to point back to that specific result. It would require adding a new `Back to search results` button on the detail page, and users would have to understand that they need to use that button and not the browser's `Back` button for navigation, but with that understanding I think we could get this done in 2 hours.
