### ISSUE TITLE
visually differentiate visited documents from those not visited

### ISSUE THREAD

**Issue by glw** [fpdcc/document-search#56]
User feedback:
"In the search results page is there some way to indicate which “view details” you recently selected.  I have a short memory span and find myself having a Ground Hog Day with the detail documents – opening and reviewing a detail document and returning back to the search page and then opening and reviewing the same detail document time after time.  "

**Comment by jeancochrane** [comment]
A super easy way to do this would just be to add [`:visited` link styles](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited) to all search result links. The downside is that we wouldn't have fine-grained control over how long the `:visited` styles would last (it's [usually tied to your browsing history](https://stackoverflow.com/a/2751815) so it would be on the user to clear browsing history to reset the styles) but with this approach I think we could get a fix up and deployed within an hour.
