### ISSUE TITLE
Make view details link easier to see

### ISSUE THREAD

**Issue by jeancochrane** [fpdcc/document-search#61]
Right now the `View details` link for search results is far to the right-hand side of the table, which makes it difficult to view on smaller screens. Try pushing it to the left-hand side instead.

**Comment by jeancochrane** [comment]
This was a very simple change so I pushed it directly to staging. Let me know how it looks to you @glw and we can push it to production if it feels better.

**Comment by glw** [comment]
hi jean, this looks good. lets push it to production

**Comment by glw** [comment]
hi jean, can we move this to production?

**Comment by jeancochrane** [comment]
Absolutely! Sorry I missed this. I just drafted a new release, which will push this into production: https://github.com/fpdcc/document-search/releases/tag/v0.1.4

**Comment by glw** [comment]
Awesome! No problem at all!
