### ISSUE TITLE
"Back to search results" disappears after editing

### ISSUE THREAD

**Issue by glw** [fpdcc/document-search#79]
Before editing
![image](https://user-images.githubusercontent.com/556205/134381933-add0cb43-5c17-432b-a44c-9067766ef296.png)

After editing *Link back to search results is gone
![image](https://user-images.githubusercontent.com/556205/134382305-35a98075-cc7e-4c59-a40d-5eeb23c17f8b.png)

**Comment by xmedr** [comment]
I just double-checked to make sure, and this has been resolved by #96.
