### ISSUE TITLE
Required fields need a more prominent visual to make sure there not missed

### ISSUE THREAD

**Issue by glw** [fpdcc/document-search#87]
As title says.

**Comment by xmedr** [comment]
Hey @smcalilly, I've spent some time thinking about this. With the way we're rendering the forms with the `crispy` tag, I'm unsure of how to add structure to each rendered field group. (My initial thought was it would be neat to add something like what they have here: https://bootsnipp.com/snippets/r8k66 )

So instead, as of now my first draft solution is to add a note at the top of the form mentioning required fields, change the color of the asterisk and increase the font size just a bit. It's a less flashy solution, but of course a much more common one. What do you think?



![Image](https://github.com/fpdcc/document-search/assets/114717958/1c52d559-05d9-46a1-bb75-0c2a9a0bc78f)

**Comment by smcalilly** [comment]
@xmedr I think your screenshot works. It's a familiar pattern for users and doesn't take much on our end to do. We can improve it if we get feedback that it's not good enough.
